# Generated by Django 3.2.14 on 2022-08-05 15:04

from django.db import migrations, models
import phonenumber_field.modelfields
import users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('profile_image', models.ImageField(blank=True, upload_to='images/user/profile')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('per_agent', models.BooleanField(blank=True, default=False, verbose_name='Переключить звонки и сообщения на агента')),
                ('is_blacklist', models.BooleanField(blank=True, default=False, verbose_name='Черный список')),
                ('is_developer', models.BooleanField(blank=True, default=False, verbose_name='Застройщик')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('notification', models.CharField(choices=[('Мне', 'Мне'), ('Мне и агенту', 'Мне и агенту'), ('Агенту', 'Агенту'), ('Отключить', 'Отключить')], default='Мне', max_length=12, verbose_name='Уведомления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', users.managers.CustomUserManager()),
            ],
        ),
    ]
