# Generated by Django 3.2.14 on 2022-09-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220816_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='purpose',
            field=models.CharField(choices=[('Дом', 'Дом'), ('Квартира', 'Квартира'), ('Коммерческие помещения', 'Коммерческие помещения'), ('Офисное помещение', 'Офисное помещение')], default='Квартира', max_length=26, verbose_name='Назначение'),
        ),
    ]
