# Generated by Django 3.2.14 on 2022-09-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_filter_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='type_housing',
            field=models.CharField(choices=[('Все', 'Все'), ('Новостройки', 'Новостройки'), ('Вторичный рынок', 'Вторичный рынок'), ('Коттеджи', 'Коттеджи')], default='Все', max_length=20, verbose_name='Вид недвижимости'),
        ),
        migrations.AlterUniqueTogether(
            name='filter',
            unique_together={('user', 'type_housing')},
        ),
    ]
