# Generated by Django 3.2.14 on 2022-09-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220908_1341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filter',
            unique_together=set(),
        ),
    ]
