# Generated by Django 3.2.14 on 2022-09-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_filter_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ('id',)},
        ),
    ]
