# Generated by Django 3.2.14 on 2022-09-14 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_filter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='area_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='area_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='district',
            field=models.CharField(blank=True, max_length=150, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='microdistrict',
            field=models.CharField(blank=True, max_length=150, verbose_name='Микрорайон'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='price_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='price_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='type_housing',
            field=models.CharField(choices=[('Все', 'Все'), ('Новостройки', 'Новостройки'), ('Вторичный рынок', 'Вторичный рынок'), ('Коттеджи', 'Коттеджи')], max_length=20, verbose_name='Вид недвижимости'),
        ),
    ]
