# Generated by Django 3.2.14 on 2022-08-30 07:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='date_start',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ImageField(blank=True, upload_to='images/housing/apartment/plan')),
                ('plan_floor', models.ImageField(blank=True, upload_to='images/housing/apartment/plan_floor')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_to_meter', models.PositiveIntegerField()),
                ('corpus', models.PositiveIntegerField(verbose_name='Корпус')),
                ('section', models.PositiveIntegerField(verbose_name='Секция')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('riser', models.PositiveIntegerField(verbose_name='Cтояк')),
                ('is_booked', models.BooleanField(default=False)),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_apartment', to='ads.announcement')),
            ],
        ),
    ]
