# Generated by Django 3.2.14 on 2022-09-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20220830_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='advertising',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='balcony_or_loggia',
            field=models.BooleanField(default=False, verbose_name='Балкон/лоджия'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='count_view',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='purpose',
            field=models.CharField(choices=[('Дом', 'Дом'), ('Квартира', 'Квартира'), ('Коммерческие помещения', 'Коммерческие помещения'), ('Офисное помещение', 'Офисное помещение')], default='Квартира', max_length=26, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='corpus',
            field=models.PositiveIntegerField(default=1, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.PositiveIntegerField(default=1, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='riser',
            field=models.PositiveIntegerField(default=1, verbose_name='Cтояк'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='section',
            field=models.PositiveIntegerField(default=1, verbose_name='Секция'),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('corpus', 'number')},
        ),
    ]
