# Generated by Django 3.2.14 on 2022-09-12 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20220908_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryannouncement',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='corpus',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='riser',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cтояк'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='section',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='galleryannouncement',
            name='image',
            field=models.ImageField(upload_to='images/ads/gallery/announcements'),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together=set(),
        ),
    ]
