# Generated by Django 3.2.14 on 2022-08-05 15:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(verbose_name='Описание')),
                ('commissioning_date', models.DateField(auto_now_add=True)),
                ('is_commissioning', models.BooleanField(default=True)),
                ('district', models.CharField(max_length=150)),
                ('microdistrict', models.CharField(blank=True, max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('map_lat', models.DecimalField(decimal_places=8, max_digits=12)),
                ('map_lon', models.DecimalField(decimal_places=8, max_digits=12)),
                ('distance', models.PositiveIntegerField(verbose_name='Высота потолков')),
                ('ceiling_height', models.FloatField()),
                ('gas', models.BooleanField(verbose_name='Газ')),
                ('status', models.CharField(choices=[('Квартиры', 'Квартиры'), ('Офисы', 'Офисы'), ('Торговые помещения', 'Торговые помещения')], default='Квартиры', max_length=18, verbose_name='Статус ЖК')),
                ('type_house', models.CharField(choices=[('Многоквартирный', 'Многоквартирный'), ('Клубный', 'Клубный(Малоквартирный)')], default='Многоквартирный', max_length=15, verbose_name='Вид дома')),
                ('class_house', models.CharField(choices=[('Элитный', 'Элитный'), ('Средний', 'Средний'), ('Бюджет', 'Бюджет')], default='Средний', max_length=7, verbose_name='Класс дома')),
                ('technology', models.CharField(choices=[('Монолитный каркас с керамзитно-блочным заполнением', 'Монолитный каркас с керамзитно-блочным заполнением'), ('Каркасно-панельное', 'Каркасно-панельное строительство'), ('Монолитно-панельное', 'Монолитно-панельное')], default='Монолитный каркас с керамзитно-блочным заполнением', max_length=60, verbose_name='Технология строительства')),
                ('territory', models.CharField(choices=[('Закрытая охраняемая', 'Закрытая охраняемая'), ('Закрытая', 'Закрытая'), ('Открытая', 'Открытая')], default='Открытая', max_length=19, verbose_name='Территория')),
                ('communal_payments', models.CharField(choices=[('Платежи', 'Платежи'), ('Предоплата', 'Предоплата')], default='Платежи', max_length=10, verbose_name='Коммунальные платежи')),
                ('heating', models.CharField(choices=[('Центральное', 'Центральное'), ('Автономное', 'Автономное'), ('Альтернативное', 'Альтернативное')], default='Центральное', max_length=14, verbose_name='Отопление')),
                ('sewerage', models.CharField(choices=[('Центральная', 'Центральная'), ('Альтернативная', 'Альтернативная')], default='Центральная', max_length=14, verbose_name='Канализация')),
                ('water_service', models.CharField(choices=[('Центральное', 'Центральное'), ('Альтернативное', 'Альтернативное')], default='Центральное', max_length=14, verbose_name='Водоснабжение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_residential_complex', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialComplexNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='housing.residentialcomplex')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialComplexBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playground', models.BooleanField(default=False)),
                ('sportsground', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('territory_protected', models.BooleanField(default=False)),
                ('residential_complex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='housing.residentialcomplex')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationAndPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formalization', models.CharField(max_length=150, verbose_name='Оформление')),
                ('payment_options', models.CharField(max_length=150, verbose_name='Варианты расчета')),
                ('purpose', models.CharField(max_length=150, verbose_name='Назначение')),
                ('contract_sum', models.CharField(max_length=150, verbose_name='Сумма в договоре')),
                ('residential_complex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_and_payment', to='housing.residentialcomplex')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryResidentialComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/housing/gallery/complex')),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_residential_complex', to='housing.residentialcomplex')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='files/housing/document')),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='housing.residentialcomplex')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ImageField(upload_to='images/housing/apartment/plan')),
                ('plan_floor', models.ImageField(upload_to='images/housing/apartment/plan_floor')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('room', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('area', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(10.0)])),
                ('price', models.PositiveIntegerField()),
                ('price_to_meter', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('corpus', models.PositiveIntegerField(verbose_name='Корпус')),
                ('section', models.PositiveIntegerField(verbose_name='Секция')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('riser', models.PositiveIntegerField(verbose_name='Cтояк')),
                ('is_booked', models.BooleanField(default=False)),
                ('decoration', models.CharField(choices=[('Черновая', 'Черновая'), ('Ремонт от застройщика', 'Ремонт от застройщика'), ('В жилом состоянии', 'В жилом состоянии')], default='Черновая', max_length=21)),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='housing.residentialcomplex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_apartment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('corpus', 'section'), ('section', 'floor')},
            },
        ),
    ]
