# Generated by Django 3.2.14 on 2022-08-22 07:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_auto_20220816_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='plan',
            field=models.ImageField(blank=True, upload_to='images/housing/apartment/plan'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='plan_floor',
            field=models.ImageField(blank=True, upload_to='images/housing/apartment/plan_floor'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='residential_complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment', to='housing.residentialcomplex'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='ceiling_height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='distance',
            field=models.PositiveIntegerField(verbose_name='Расстояние до моря'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='map_lat',
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='map_lon',
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together=set(),
        ),
    ]
