# Generated by Django 3.2.14 on 2022-08-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_auto_20220822_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryresidentialcomplex',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
