# Generated by Django 3.2.14 on 2022-08-30 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housing', '0005_auto_20220830_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialcomplex',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_residential_complex', to=settings.AUTH_USER_MODEL),
        ),
    ]
