# Generated by Django 3.2.14 on 2022-09-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_alter_residentialcomplex_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentialcomplex',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='corpus',
            field=models.PositiveIntegerField(null=True, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='floor',
            field=models.PositiveIntegerField(null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='riser',
            field=models.PositiveIntegerField(null=True, verbose_name='Cтояк'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='section',
            field=models.PositiveIntegerField(null=True, verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='gas',
            field=models.BooleanField(default=True, verbose_name='Газ'),
        ),
    ]
